name: Echo Name and View Artifact

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Name into File
        run: echo "${{ vars.NAME }}" > name.txt

      - name: Save Name File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: name-file
          path: name.txt

  view-file:
    runs-on: ubuntu-latest
    needs: create-file
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: name-file
          path: .

      - name: Display File Content
        run: cat name.txt